#!/bin/bash
host="http://localhost:5000"
event=$1
arg=$2

echo "Send event $event: $arg"
case $event in
new-pdf)      curl --location "$host/new-pdf/$arg";;
new-citation) curl --data "citation=$arg" "$host/new-citation";;
*) echo "Unknown event "$event", try: new-pdf, new-citation";;
esac
