#!env python3
import re
regex = re.compile("(?P<doi>10\.\d{4,9}/[-._;()/:A-Z0-9]+)", re.IGNORECASE)

import fitz
def extract_doi(pdf_file):
  with fitz.open(pdf_file) as docs:
    for page in docs:
      txt = page.getText()
      doi = re.search(regex, txt)
      if doi:
        return doi.group("doi")
  return None

from sys import argv, exit
if __name__ == '__main__':
  if len(argv) > 1:
    doi = extract_doi(argv[1])
    if doi:
      print(f"[+] Found DOI: {doi}")
      exit(0)
    else:
      print("[!] Couldn't find DOI")
      exit(1)
  else:
    print("""\
reader [PDF file]\
          """)
